### ISSUE TITLE
Color Function

### ISSUE THREAD

**Issue by Dan-Look** [FractalVoyager/FractalVoyager#3]
The color bar at the bottom doesn't seem to update the color of the compiled fractal.

**Comment by dbryan17** [comment]
Hello Dan, to avoid having many redraws that cause the app to slow down as the user pulls the slider, you must use the "update" button in the top portion of the screen. So, to change the color: drag the slider to the desired color, then the "update" button will illuminate yellow, and a click on that will update the color of the fractal.

**Comment by Dan-Look** [comment]
Thanks, Cody! It wasn’t working earlier today, but it is now, so it may have been a reload issue!

==================
Daniel M Look
Rutherford Professor of Mathematics
Department of Mathematics, Computer Science, and Statistics
St. Lawrence University
https://sites.google.com/view/dmlook/home

Pronouns: he, him, his

From: Dakota Bryan ***@***.***>
Reply-To: FractalVoyager/FractalVoyager ***@***.***>
Date: Monday, August 28, 2023 at 11:21
To: FractalVoyager/FractalVoyager ***@***.***>
Cc: Daniel Look ***@***.***>, Author ***@***.***>
Subject: Re: [FractalVoyager/FractalVoyager] Color Function (Issue #3)

CAUTION: This email message originated from outside of St. Lawrence University. Please do not click links, follow instructions or open attachments unless you recognize the sender and know the content is safe.


Hello Dan, to avoid having many redraws that cause the app to slow down as the user pulls the slider, you must use the "update" button in the top portion of the screen. So, to change the color: drag the slider to the desired color, then the "update" button will illuminate yellow, and a click on that will update the color of the fractal.

**Comment by dbryan17** [comment]
No problem, yes it's pretty buggy at the moment. Thanks for submitting an issue. I have a list of bugs that I'm working through fixing on the README file; if you find any others, please open more issues!
