### ISSUE TITLE
Entering starting value for parameter plane

### ISSUE THREAD

**Issue by Dan-Look** [FractalVoyager/FractalVoyager#4]
For parameter planes other than z^2+c the point we choose to iterate for each c value is often not 0. 

So, with the Mandelbrot set we are, for each c, basically looking at the orbit c, c^2+c, (c^2+c)^2+c, ... and asking whether it escapes. However, for other fractals we would not want z=0 to be the initial output. In general, the initial input needs to be a critical point of the original function. Is there a way to enter the initial value?

In FractalStream the code would look something like this:
set par z=1.
iterate z^2+c until z escapes.

or

par z=1.
iterate z^2+c until z escapes.

(Let's not worry about the difference between using "set" or not at this time.). :)

**Comment by dbryan17** [comment]
Hello Dan, This is somewhat implemented in the current version, but the equals sign does not work, and par comes before set. So, 
"
par set z to 1.
iterate z^2+c until z escapes.
"
works in the current version. There is no language documentation currently, so I created a repository in the "FractalVoyager" organization for sample scripts and added some there. I based the language almost exactly off of fractal stream (although many features they have we don't yet), so the docs at https://code.google.com/archive/p/fractalstream/downloads can be helpful. 

I've been slowly working through some glaring bugs in the app, but once I finish those up I hope to put together some language documentation so you know what Fractal Voyager can and can't do, and how to do it.

**Comment by Dan-Look** [comment]
Thanks so much, Cody! This is all great!

==================
Daniel M Look
Rutherford Professor of Mathematics
Department of Mathematics, Computer Science, and Statistics
St. Lawrence University
https://sites.google.com/view/dmlook/home

Pronouns: he, him, his

From: Dakota Bryan ***@***.***>
Reply-To: FractalVoyager/FractalVoyager ***@***.***>
Date: Tuesday, September 12, 2023 at 20:30
To: FractalVoyager/FractalVoyager ***@***.***>
Cc: Daniel Look ***@***.***>, Author ***@***.***>
Subject: Re: [FractalVoyager/FractalVoyager] Entering starting value for parameter plane (Issue #4)

CAUTION: This email message originated from outside of St. Lawrence University. Please do not click links, follow instructions or open attachments unless you recognize the sender and know the content is safe.


Hello Dan, This is somewhat implemented in the current version, but the equals sign does not work, and par comes before set. So,
"
par set z to 1.
iterate z^2+c until z escapes.
"
works in the current version. There is no language documentation currently, so I created a repository in the "FractalVoyager" organization for sample scripts and added some there. I based the language almost exactly off of fractal stream (although many features they have we don't yet), so the docs at https://code.google.com/archive/p/fractalstream/downloads<https://code.google.com/archive/p/fractalstream/downloads> can be helpful.

I've been slowly working through some glaring bugs in the app, but once I finish those up I hope to put together some language documentation so you know what Fractal Voyager can and can't do, and how to do it.
